name: pics

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v3  # Use v3 of the flutter action
        with:
          flutter-version: '3.24.3'  # Explicit version
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: android-30
          build-tools: 30.0.3
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
